/*

 NUMSET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 1 to 11

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __numset_h_INCLUDE
#define __numset_h_INCLUDE

/* Bank of tiles. */
#define numsetBank 0
/* Start of tile array. */
extern const unsigned char numset[];

#endif

/* End of NUMSET.H */
